name: Command via SSH
on: push
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: "Root"
          SSH_KEY: ${{ secrets.SERVER.SSH }}
          SSH_HOST: ${{ secrets.DROPLET_ADDRESS }}

      - name: Stop the server
        run: ssh staging 'sudo systemctl stop nginx'

      - name: Check out the source
        run: ssh staging 'cd django/CD-TEST/myproject && git fetch && git reset --hard origin/main'

      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'sudo systemctl start nginx'
